name: Loc
version: 0.0.1
description: Loc allows you to save locations in your world.
author: zaned
main: sh.zane.loc.Loc
website: https://zane.sh/loc
api-version: "1.15"
commands:
  loc:
    description: View, save, & edit your locations.
    usage: "Usage: /loc [list|save|remove|rename]"
    permission: loc.loc
    permission-message: You don't have permission!
permissions:
  loc.save:
    description: Save personal locations.
    default: true
  loc.remove:
    description: Remove personal locations.
    default: true
  loc.rename:
    description: Rename locations.
    default: true
  loc.list:
    description: List personal locations.
    default: true
  loc.*:
    description: Allows everything.
    default: op
    children:
      loc.save: true
      loc.remove: true
      loc.rename: true
      loc.list: true